language: python

matrix:
    include:
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: TOXENV=py35

script:
    - |
      export HOMEBREW_NO_AUTO_UPDATE=1
      brew tap
      brew untap caskroom/cask
      brew untap homebrew/core
      brew untap doesnt/exist
      brew tap
      brew update
      brew search pyenv
      ls
      exit
      brew install linuxbrew-core/pyenv
      #brew info pyenv
      brew install pyenv
      brew upgrade pyenv
      (
        cd /tmp
        git clone --depth=1 https://github.com/Homebrew/install
        ruby install/uninstall --force
        bash install/install.sh
      )
      brew --help
      brew update
      brew install pyenv
      brew upgrade pyenv
