language: python

matrix:
    include:
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: TOXENV=py35

script:
    - |
      export HOMEBREW_NO_AUTO_UPDATE=1
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" --force
      brew --help
      brew update
      brew install pyenv
      brew upgrade pyenv
